baseURL = "https://twopartscode.com/"
languageCode = "en-us"
title = "Two Parts Code"
theme = "hugo-PaperMod"

[params]
  description = "Blog meta description."
  githubUsername = "clone1018"
  twitterUsername = "clone1018"
  tagline = "Blog tagline. Shown under index title."
