baseURL = "https://twopartscode.com/"
languageCode = "en-us"
title = "TwoPartsCode"
theme = "hugo-PaperMod"

[params]
  description = "Programming cookbooks, live tutorials, and more!"
  githubUsername = "clone1018"
  twitterUsername = "clone1018"
  showReadingTime = true

[params.homeInfoParams]
  title = "Two Parts Code, One Part Love"
  content = "Programming Cookbooks, Live Tutorials, and more!"

[[menu.main]]
identifier = "events"
name = "Live Events"
url = "/events/"
